### DISCUSSION TITLE
使用Github Action编译mpv(win)

### DISCUSSION THREAD

**Discussion by zhongfly** [hooke007/mpv_PlayKit#27] [INFO 信息]
https://github.com/zhongfly/mpv-winbuild
欢迎有需要的人下载/star

**Comment by dyphire** [comment]
这是因为`Ubuntu`自带的`autoconf`版本不够，自带的包版本为2.69，`mingw-w64-crt.cmake`需要`autoconf`版本在2.71以上，需要自行卸载安装更高版本的`autoconf`才能正常编译。我使用`wsl`时也遇到了这个问题，后面可能还会遇到`vulkan patch`编译失败

`autoconf`的卸载更新命令参考，应在构建环境前先执行
```
sudo apt-get remove autoconf
wget http://mirrors.kernel.org/gnu/autoconf/autoconf-2.71.tar.xz
tar -xvf autoconf-2.71.tar.xz
cd autoconf-2.71
./configure --prefix=/usr/
make&&make install
```

**Reply by zhongfly** [reply]
vulkan patch 好像我在其他地方遇到过，是没设置git用户名和邮箱导致的吗？

**Reply by dyphire** [reply]
> vulkan patch 好像我在其他地方遇到过，是没设置git用户名和邮箱导致的吗？

我也没搞明白，至今也没解决这问题。从[mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake)的issue和commits的日志来看，`vulkan patch`经常出现，怀疑是上游更新频繁，shinchiro还没修复

**Reply by zhongfly** [reply]
```shell
  sudo apt-get remove autoconf
  wget http://mirrors.kernel.org/gnu/autoconf/autoconf-2.71.tar.xz
  tar -xvf autoconf-2.71.tar.xz
  cd autoconf-2.71
  ./configure --prefix=/usr/
  sudo make && sudo make install
```
还是会有一样的错误……

应该是还需要设置系统变量吧……我实在不熟悉

**Reply by dyphire** [reply]
估计是了，我在wsl上已经可以正常编译成功了

**Reply by zhongfly** [reply]
用autoconf --version得到版本号是2.71，结果一样报错，太奇怪了
autoconf版本号 https://github.com/zhongfly/mpv-build/runs/3781643013?check_suite_focus=true#step:5:580
失败：https://github.com/zhongfly/mpv-build/runs/3781643013?check_suite_focus=true

**Reply by zhongfly** [reply]
我又手动从源码编译安装了automake
mingw-w64-crt这里不报错了，但是Performing autoreconf step for 'lame'时又报错了

**Reply by dyphire** [reply]
绝了，期待折腾明白，等着抄作业

看到安装了`automake`，我想起来了，卸载`autoconf`时，它会连带卸载`automake`、`libtool`和`libffi-dev`，所以我当时安装更新版本的`autoconf`后，还执行了以下安装命令把后三者重新安装回来：
```
sudo apt-get install automake libtool libffi-dev
```
最好在以下构建环境前进行以上操作，以免有其他依赖误删的

```
apt-get install build-essential checkinstall bison flex gettext git mercurial subversion ninja-build gyp cmake yasm nasm automake pkg-config libtool libtool-bin gcc-multilib g++-multilib clang libgmp-dev libmpfr-dev libmpc-dev libgcrypt-dev gperf ragel texinfo autopoint re2c asciidoc python3-pip docbook2x unzip p7zip-full curl

pip3 install rst2pdf mako meson==0.59.0rc2
```

**Reply by zhongfly** [reply]
我看了下，并没有删除libtool libffi-dev
```
The following packages will be REMOVED:
  autoconf automake libltdl-dev libmagickcore-6.q16-dev libmagickcore-dev
  libmagickwand-6.q16-dev libmagickwand-dev php7.4-dev php8.0-dev unixodbc-dev
```
出现安装一遍全部依赖的话，怀疑会覆盖掉手动编译的版本

**Reply by dyphire** [reply]
应该不会，构建环境中没有autoconf

**Comment by dyphire** [comment]
vulkan patch 问题上游修复了，[#144](https://github.com/shinchiro/mpv-winbuild-cmake/issues/144)需要手动解决
```
pip3 install rst2pdf mako meson==0.59.0rc2
````

**Comment by zhongfly** [comment]
开发者建议用gcc10分支，但是遇到mujs编译失败，翻issue说是偶尔这样……我多试试吧

**Reply by zhongfly** [reply]
mujs不是偶发，每次必出现，目前卡在libsrt的编译了
```
[192/595] Creating directories for 'libsrt'
[193/595] Performing download step (git clone) for 'libsrt'
[194/595] No update step for 'libsrt'
[195/595] Performing force-update step for 'libsrt'
[196/595] Performing patch step for 'libsrt'
Applying: avoid name collision
[197/595] Performing configure step for 'libsrt'
FAILED: packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure 
cd /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt && /usr/local/bin/cmake -P /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure-.cmake && /usr/local/bin/cmake -E touch /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure
CMake Error at /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure-.cmake:49 (message):
  Command failed: 1

   '/home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/exec' 'cmake' '-H/home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt' '-B/home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt' '-G' 'Ninja' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_INSTALL_PREFIX=/home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/install/mingw' '-DCMAKE_TOOLCHAIN_FILE=/home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/toolchain.cmake' '-DENABLE_STDCXX_SYNC=ON' '-DENABLE_APPS=OFF' '-DENABLE_SHARED=OFF'

  See also

    /home/runner/work/mpv-build/mpv-build/mpv-winbuild-cmake/build64/packages/libsrt-prefix/src/libsrt-stamp/libsrt-configure-*.log
```

**Comment by zhongfly** [comment]
已经成功了，还在修改细节

**Comment by dyphire** [comment]
抄作业改了个[mpv-winbuild](https://github.com/dyphire/mpv-winbuild)出来。上午测试编译和打包上传成功了，下午再运行就卡在最后一步mpv构建了，~怀疑是上游构建脚本出问题了待shinchiro修复~

是上游libplacebo库更新的锅，mpv合并相应pr后已正常

**Comment by zhongfly** [comment]
libsrt的问题应该解决了……看来只有mujs的奇怪问题了，必须`ninja -C $buildroot/build$bit mujs || ninja -C $buildroot/build$bit mujs-removebuild && ninja -C $buildroot/build$bit mujs`

**Comment by dyphire** [comment]
发现了另一种使用Github Action编译mpv-win的方式：[eko5624/mpv-win64](https://github.com/eko5624/mpv-win64)

优点：编译速度比shinchiro版快很多，依赖采用动态库链接
缺点：没有libmpv编译

**Reply by zhongfly** [reply]
慢就慢吧，我还是需要libmpv的

**Reply by hooke007** [reply]
比它快的原因大部分是少了很多packages，依赖少了，自然体积小了，功能少了（比如没有编码器

**Reply by dyphire** [reply]
嗯，readme里有说明，减少了编码器和fontconfig等依赖选项

**Reply by zhongfly** [reply]
你说的那个也是主要修改自 https://github.com/nyfair/mpv-win64 都是国人 https://github.com/nyfair/mpv-win64/issues/4

**Reply by dyphire** [reply]
是的，这个修改版更像shinchiro版。用的packages主要都是git最新代码，而不是releases版。这么做的好坏都挺明显

**Comment by zhongfly** [comment]
问一下：在实际机子上，编译过一次后，假如mpv-winbuild-cmake更新了，是不是需要按照第一次的步骤重新来一遍，还是直接ninja update后ninja mpv呢？ @hooke007 @dyphire

**Reply by hooke007** [reply]
更新repo， 然后ninja update，ninja mpv

**Reply by zhongfly** [reply]
> 更新repo， 然后ninja update，ninja mpv

我刚看了项目里的autobuild.sh，感觉还需要`cmake -DTARGET_ARCH=x86_64-w64-mingw32 -G Ninja ..` 我大概清楚了

**Comment by zhongfly** [comment]
https://www.githubstatus.com/incidents/bdbzpz7qxmbx 原来是github action挂了，我说怎么运行不了……

打算加上cache缓存，可以快一点，类似与实机第二次编译

**Reply by zhongfly** [reply]
基本搞定，各依赖变化不大的话，可以直接把时间从一个半小时缩短到半个小时

**Reply by zhongfly** [reply]
![image](https://user-images.githubusercontent.com/11155705/136144419-2ea9e970-c936-4aeb-ab53-755d98d517fe.png)

**Comment by zhongfly** [comment]
@hooke007  请问最近你在实体机上编译是否遇到问题？
我发现用ubuntu 22.04的docker镜像+gcc11分支时，Performing download step (SVN checkout) for 'amf-headers'这一步耗时极长，且必定失败
```
svn: E170013: Unable to connect to a repository at URL 'https://github.com/GPUOpen-LibrariesAndSDKs/AMF/trunk/amf/public/include'
svn: E000110: Error running context: Connection timed out
```
诡异的是actions环境中（ubuntu 20.04）编译gcc10分支却是正常的

如果方便的话，能否在实体机上测试下用ubuntu 22.04+gcc11构建amf-headers`ninja amf-headers-fullclean` `ninja amf-headers`？

**Reply by zhongfly** [reply]
看你的失败记录也是如此 https://github.com/hooke007/mpv-winbuild/runs/4450384881?check_suite_focus=true#step:5:3147 amf-headers这个没有构建成功，只创建了文件夹，卡在了更新源码

**Reply by hooke007** [reply]
....我的实机中gcc11分支就没成功过，永远卡在无法编译openal-soft那一步，现在也全是用action的

**Reply by zhongfly** [reply]
> 

@hooke007 
我目前测试发现好像是22.04版本上的svn有问题
测试代码：
docker:`docker run --rm ubuntu:22.04 /bin/bash -c "apt-get update && apt-get install -y subversion && svn --version && svn co https://github.com/GPUOpen-LibrariesAndSDKs/AMF/trunk/amf/public/include --non-interactive amf-headers"`
或者：
```shell
apt-get install -y subversion
svn co https://github.com/GPUOpen-LibrariesAndSDKs/AMF/trunk/amf/public/include --non-interactive amf-headers
```

**Reply by zhongfly** [reply]
进展：我将问题发到了svn的邮件列表里，别人也确实复现了这个问题…看来的确让我遇到了bug

**Reply by zhongfly** [reply]
可以先用archlinux+gcc11 已经完全测试过了（主分支已更换为arch）
要不就用回ubuntu20 + gcc10

**Reply by nyfair** [reply]
用subversion下载git这用法感觉怪怪的，只需要单一目录可以这样
```git clone --depth 1 --sparse https://github.com/GPUOpen-LibrariesAndSDKs/AMF amf-headers && cd amf-headers && git sparse-checkout set amf/public/include```

**Reply by hooke007** [reply]
太怪了，因为是action我看不到你的openal编译详细记录，但是我所有的实机上arch系统编译都没法通过，看了看action装的包我又一个不缺，我怀疑是桌面环境搞的鬼

**Reply by zhongfly** [reply]
> 用subversion下载git这用法感觉怪怪的，只需要单一目录可以这样 `git clone --depth 1 --sparse https://github.com/GPUOpen-LibrariesAndSDKs/AMF amf-headers && cd amf-headers && git sparse-checkout set amf/public/include`

可能是用cmake这么做比较麻烦吧，毕竟svn一个语句就解决了。github本来就支持svn，所以正常来说也应该是没问题的。

**Reply by zhongfly** [reply]
> 太怪了，因为是action我看不到你的openal编译详细记录，但是我所有的实机上arch系统编译都没法通过，看了看action装的包我又一个不缺，我怀疑是桌面环境搞的鬼

需要log的话改一下就好了：
```yaml
      - name: Collect logs
        if: ${{ always()}}
        run: |
          sudo 7z a logs.7z mpv-winbuild-cmake/build${{ matrix.bit }}/*.log -r
      - name: upload logs
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: logs
          path: logs.7z
```
始终上传log，并且是上传所有log（原先为仅上传带err名称的）

**Reply by hooke007** [reply]
> 我怀疑是桌面环境搞的鬼

有点关系但不大。装桌面环境的时候附带把pipewire给我强制装了，完全卸载pipewire就顺利编译了，但是看日志好像仍然在尝试编译linux上用的后端。。。应该是cmake里缺少限定的args
_(然而比较新的linux的桌面环境都附带了pipewire)_

**Reply by hooke007** [reply]
action怎么更新cache，我之前的cache被我玩烂了，只要开cache必定编译失败

**Reply by zhongfly** [reply]
> action怎么更新cache，我之前的cache被我玩烂了，只要开cache必定编译失败

触发ations时有选项啊，第一个框里有任何字符都是告诉脚本删除缓存，完全重新编译的…
![Screenshot_20211211072154](https://user-images.githubusercontent.com/11155705/145653400-f3ef262e-9bbd-4021-83cb-c56b2b696170.png)
同时配合第二个空，将新生成的cache保存到全新的key上。

https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
整个过程是先让它下载缓存，但根据第一个参数，编译脚本运行时会删除所有已存在文件，完全 重新编译，编译完后，用全新的key保存新得到的cache(因为相同的key不会被覆盖，只会忽略新产生的)

还是建议你看一下这个cache的文档，就明白了

**Reply by zhongfly** [reply]
> action怎么更新cache，我之前的cache被我玩烂了，只要开cache必定编译失败

还有一个事，某个cache要是7天没被使用，就会被删除
或者保存新cache时不够存储空间，会清理旧cache直到腾出足够的空间

**Reply by hooke007** [reply]
（我以为这个也是clean workflow

**Reply by zhongfly** [reply]
https://github.com/CharlesMengCA/mpv-player-only (encoders disabled to get smaller binaries)
可以直接试试这个，或者按这个改一些设置

**Reply by hooke007** [reply]
他这个肯定没问题的，因为也没有桌面环境，只要安装桌面环境openal-soft就很莫名其妙会编译一些用不到的后端。昨天也改了改去掉了aom，x264，x265，nvenc这几个libmpv用不到的编码器减少了近20m的体积

edit:上上游一起解决了这个问题

**Comment by zhongfly** [comment]
github的奇怪问题：release的排序竟然不是按时间以及字符排序
如图，显示的最新是12-14，而实际最新12-16排在图的最下面？？？
如果6+个tag都打在同一个commit上，排序就奇怪起来了，而且我发现不止我一个仓库会这样，https://github.community/t/the-latest-release-show-in-release-tab-isnt-real-latest/218086
![](https://aws1.discourse-cdn.com/github/original/3X/1/9/19414f2fa31279385289f679e747a7fbd5efc76c.png)

**Reply by hooke007** [reply]
看上去他简单的认为认为14＞7。。。。

**Reply by dyphire** [reply]
我也遇到了，奇怪的release bug

**Reply by zhongfly** [reply]
https://github.com/BtbN/FFmpeg-Builds/releases 里有7个release在同一个commit上，排序就更诡异了：
2021-12-15
2021-12-14
……
2021-12-11
2021-12-17
2021-12-16

根据https://github.com/dyphire/mpv-winbuild/releases 来看，可能是16+这些数有什么特殊的地方……

**Reply by hooke007** [reply]
16是yesterday
应该是today和yesterday的时间标签没进入正常排序的序列，过两天应该就正常了（

**Reply by zhongfly** [reply]
> 16是yesterday 应该是today和yesterday的时间标签没进入正常排序的序列，过两天应该就正常了（

按这么理解的话，就永远不能正确显示最新了……

**Reply by hooke007** [reply]
这个机器人能不能把包都推到同一个release下的assets

**Reply by hooke007** [reply]
另一种思路是把所有过期的release转换成pre-release，因为最新版不计量预发行的版本号

**Reply by zhongfly** [reply]
> 这个机器人能不能把包都推到同一个release下的assets

就是更新/修改release呗，我用的那个发布action是支持的。你看文档就是了,https://github.com/ncipollo/release-action ，是全删还是覆盖同名，都可以控制

**Reply by zhongfly** [reply]
> 另一种思路是把所有过期的release转换成pre-release，因为最新版不计量预发行的版本号

这个思路只能保证最新版没问题，但其他的排序估计也还是有问题……

我是直接建一个[分支](https://github.com/zhongfly/mpv-winbuild/tree/version)，每次发布都新建一个当天的提交，然后tag打在当天的commit，这样的话每个release都是不同的commit，且时间有序
你看我今天刚发的release就是

**Comment by hooke007** [comment]
我这边是不使用缓存编译无法通过了，无论是你的分支还是我自己的精简分支

实体机0缓存编译一切正常

**Reply by zhongfly** [reply]
只能拿着日志找shinchiro了，这方面我不懂…

**Reply by zhongfly** [reply]
目前应该是https://gitlab.freedesktop.org/ 的git出了问题…https://gitlab.freedesktop.org/fontconfig/fontconfig.git 还有uchardet都git clone不了

**Reply by hooke007** [reply]
gitlab那服务器三天两头抽风，换github https://github.com/hooke007/mpv-winbuild-cmake/commit/5b07673f2ed43e99196cc61cc083248988fcaf78

**Comment by zhongfly** [comment]
shinchiro 自己做了github action

**Comment by eko5624** [comment]
@zhongfly @dyphire 现在已支持静态编译，也添加了libmpv的编译。可以作为shinchiro编译版的横向参考，算是另一种编译方案吧。原创是nyfair，我只是做了一些组件添加，尽量和shinchiro编译版的功能保持一致。

https://github.com/eko5624/mpv-win64

**Reply by zhongfly** [reply]
我觉得是不是可以合并那些组件的workflow，变成一个个脚本(安装依赖/编译)，由一个workflow从workflow_dispatch的inputs输入要编译的组件名，运行相应的脚本。进一步可以用matrix并行编译多个组件

**Reply by eko5624** [reply]
其实这个build-weekly.yml就是并行编译组件的。因为我对bash脚本语言不太精通，所以看起来比较臃肿，还有很多需要优化的地方。可以大家一起优化下。

**Reply by dyphire** [reply]
其实我很欣赏这种编译方式，只不过它缺失了很多重要依赖，有待完善。

比如认为不需要的x264/x265等编码器的缺失破坏了screenshot等功能和一些第三方lua脚本。

再比如libass的构建缺少了关键的libiconv和libunibreak依赖，前者是https://github.com/libass/libass/pull/583 实现的更强大字体识别功能的基础；后者则是近期libass合并的 https://github.com/libass/libass/pull/486 新增的依赖库，实现了不间断文本的自动断行换行防止溢出屏幕。不过libass的ASS_Feature相关特性mpv尚未支持，我在个人修改版mpv上尝试实现了相关功能：https://github.com/dyphire/mpv/commit/4f1192690b10e247c56298f095131264fdcd4616 ， 相关编译见：[mpv_own-2022-08-21](https://github.com/dyphire/mpv-winbuild/releases/tag/mpv_own-2022-08-21)

ps: 相关代码实现有点问题，不适合提交pr，仅供测试功能。同时libass的ass_track_set_feature的api改进尚未完成

**Reply by hooke007** [reply]
x264/x265不影响截图screenshot，截图用的是png和jpg库

**Reply by dyphire** [reply]
缺少的某个依赖影响webp截图，我之前测试会失败(跟x264/x265无关
当然也有可能是libwebp自身的问题，我测试的编译版本可能正好遇到了libwebp出问题的版本

**Reply by eko5624** [reply]
libunibreak已经加进去了。我把libiconv也加进去吧。

**Reply by dyphire** [reply]
确实有，看漏了。虽然shinchiro也第一时间添加了libunibreak，但由于mpv尚未支持libass的ASS_Feature的相关api，所以实际上不基于修改版mpv编译的话还用不到也没有相关功能（

有趣的是libass的ass_track_set_feature的api实际上是mpv开发者wm4添加的

**Reply by nyfair** [reply]
为啥明明没有@我，github还是发了通知，那我也来说点
1. 一方面Apache553提交的补丁里除了iconv的实现同时也提供了标准windows api的实现，另一方面ucrt runtime原生使用windows unicode api, 引入iconv没有必要
2. ffmpeg不需要任何依赖原生支持png，但它本身并不是专业的图像处理库，格式转换以及更复杂的处理需求完全可以在脚本层面实现
3. mpv团队有自己的考量，libass的wrap_lines_smart函数本身就具备防止文字溢出的功能，引入libunibreak的实现只是枚举8国语言的unicode范围进行提前换行避免同种文字被切割，单纯移植这个也就多写10来行，离完整实现unicode 14.0换行算法相去甚远，具体到每个人的偏好上也更难去下定论

**Reply by hooke007** [reply]
> 为啥明明没有@我，github还是发了通知

先前参与过该帖讨论的都会收到通知 https://github.com/hooke007/MPV_lazy/discussions/27#discussioncomment-1784972

**Reply by dyphire** [reply]
> 3. mpv团队有自己的考量，libass的wrap_lines_smart函数本身就具备防止文字溢出的功能，引入libunibreak的实现只是枚举8国语言的unicode范围进行提前换行避免同种文字被切割，单纯移植这个也就多写10来行，离完整实现unicode 14.0换行算法相去甚远，具体到每个人的偏好上也更难去下定论

其实没有那么复杂，mpv要引入WRAP_UNICODE的特性的话也主要是用来解决https://github.com/mpv-player/mpv/issues/2203, https://github.com/libass/libass/issues/360. 也就是OSD文本和字幕溢出的问题，不需要太复杂的解决方案，没必要完全实现完整的换行算法。ASS Feature目前其他两个特性一个括号双向匹配主要服务阿拉伯语字幕一个整体文本处理主要是bidi和\fay重塑，也是有待mpv添加ass_track_set_feature的api，不过我觉得等api进一步改进后libass开发者也会向mpv提交相应实现的pr，目前该api还存在一些不足。

**Reply by dyphire** [reply]
mpv引入WRAP_UNICODE特性后有明显感知和改善的是OSD文本显示。字幕反而很少感知到，因为常规字体大小下会溢出的不规范字幕还是较少的，只有人为加大字号才会感知到行为的变化。
 OSD效果图：
![IMG_20220823_175029_062](https://user-images.githubusercontent.com/61936050/186128392-e8e8daf6-9847-49ae-ab5d-8c3d6b11f655.jpg)

**Comment by eko5624** [comment]
我的在Archlinux Docker下交叉编译版本来咯: https://github.com/eko5624/mpv-winbuild

最大的优点是可以进行并行编译，所以全新编译下来速度比shinchiro的编译速度快很多。大家可以自由选mcf线程版本和posix线程版本。暂时只提供64位的编译。它们的区别主要是使用线程不同，也可能会带来性能的些许差异，具体可以看lhmouse大佬的讲解：https://github.com/msys2/MINGW-packages/discussions/13259

目前的小瑕疵是mcf静态编译版因为libaribcaption库的原因仍然需要依赖libmcfgthread-1.dll这个动态库文件，故不算是真正意义的静态编译版本。我暂时想到的方法是选择编译libaribb24进行平替，可以算真正意义上的静态版本了。这也就是我为什么把动态编译版设置为默认分支的原因啦~

感谢这几位大佬的帮助：lhmouse, nyfair, shinchiro。在他们的帮助下，我才顺利构建了工具链。
工具链仓库：https://github.com/eko5624/toolchain

**Reply by hooke007** [reply]
你这个版本从始至终好像都没有vf_libplacebo， 你看看是不是没链接过

**Reply by eko5624** [reply]
shinchiro的有vf_libplacebo吗，如果他的没有的话我这个也没有。因为编译代码一样的。

**Reply by hooke007** [reply]
shinchiro是最近才没有的，还在调查 https://github.com/shinchiro/mpv-winbuild-cmake/issues/382 。但是我看nyfair的编译模式从一开始就没有，并不是最近才没有

**Reply by eko5624** [reply]
怎么看有没有vf_libplacebo？

**Reply by hooke007** [reply]
issue里有说明

**Reply by eko5624** [reply]
好的，我把mpv先回退到6月18号的commit https://github.com/mpv-player/mpv/commit/ee155d79fd7b669de6d91654fc84ea26aaeac892 编译一版试试看。

**Reply by zhongfly** [reply]
之前说到简化合并你workflow文件，我大概思路如下，用matrix功能来实现
然后按照依赖关系分成多个job，类似与这样：
```yml
  Lv1-dependencies:
    strategy:
      matrix:
        pkg: [amf-dev, angle-dev, avisynth-dev]
        include:
          - pkg: amf-dev
            pkg-name: amf-headers-dev
          - pkg: angle-dev
            pkg-name: angle-headers-dev
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm docker
          sudo pacman -S --noconfirm --needed git ninja cmake yasm nasm unzip p7zip python-pip python-cairo curl jq
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - name: Setting top_dir env
        run: |
          echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV         
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting makepkg etc
        run: |
          sudo cp pacman-config/makepkg_cross.conf /etc
          sudo cp pacman-config/makepkg-cross /usr/local/bin
      - name: Loading cross gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: cross-gcc-mcf-${{ github.run_id }}
          restore-keys: |
            cross-gcc-mcf-
      - name: Build
        run: |
          sudo chmod 777 -R ${{ env.top_dir }}
          sudo chmod 777 -R .
          cd ${{ matrix.pkg }}
          sudo -H -u builder makepkg-cross -sC --noconfirm
      - name: Release
        if: ${{ matrix.pkg-name }}
        env:
          GH_TOKEN: ${{ github.token }}    
        run: |
          ./release-dev.sh ${{ matrix.pkg-name }} ${{ matrix.pkg }}
      - name: Release
        if: ${{ !matrix.pkg-name }}
        env:
          GH_TOKEN: ${{ github.token }}    
        run: |
          ./release-dev.sh ${{ matrix.pkg }} ${{ matrix.pkg }}
```

**Reply by eko5624** [reply]
ok，我参照你提供的脚本修改试试。

**Reply by eko5624** [reply]
@hooke007 确实是我的编译版本有问题。回退至 https://github.com/mpv-player/mpv/commit/ee155d79fd7b669de6d91654fc84ea26aaeac892 也没有vf_libplacebo，我先排查一下我的编译脚本。

**Reply by hooke007** [reply]
不一定是mpv的问题，我建议你把libplacebo和ffmpeg都切换到那天之前的节点

**Reply by eko5624** [reply]
解决libaribcaption依赖libmcfgthread-1.dll的问题了。需要删除工具链中的libmcfgthread.dll.a文件。然后就不会再去链接libmcfgthread.dll了。
出处：https://github.com/msys2/MINGW-packages/discussions/13259#discussioncomment-5167610

**Reply by eko5624** [reply]
@zhongfly 按照你的提示简化了一下在windows下编译的流程，如下：
```
name: build-all
defaults:
  run:
    shell: msys2 {0}

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  standalone-pkgs:
    strategy:
      matrix:
        pkg-path:
          - amf-dev
          - angle-dev
          - aom-dev
          - avisynth-dev
          - davs2-dev
          - ffnvcodec-dev
          - fribidi-dev
          - lame-dev
          - lcms2-dev
          - libbs2b-dev
          - libcaca-dev
          - libdvdcss-dev
          - libiconv-dev
          - libjpeg-dev
          - libmodplug-dev
          - libogg-dev
          - libsdl2-dev
          - libsoxr-dev
          - libspeex-dev
          - libudfread-dev
          - libunibreak-dev
          - libva-dev
          - libvpl-dev
          - libvpx-dev
          - libwebp-dev
          - libzimg-dev
          - luajit2
          - mujs
          - openal-soft-dev
          - opus-dev
          - rubberband
          - shaderc-dev
          - spirv-cross-dev
          - uavs3d-dev
          - vapoursynth
          - vulkan-dev
          - xxhash-dev
          - zlib-dev
        include:
          - { pkg-path: amf-dev, pkg-name: amf-headers-dev }
          - { pkg-path: angle-dev, pkg-name: angle-headers-dev }
          - { pkg-path: fribidi-dev, pkg-build: PKGBUILD-new }
          - { pkg-path: luajit2, pkg-name: luajit2-dev }
          - { pkg-path: rubberband, pkg-name: rubberband-dev }
          - { pkg-path: spirv-cross-dev, pkg-build: PKGBUILD-new }
          - { pkg-path: vapoursynth, pkg-name: vapoursynth-dev }
    env:
      PKG_PATH: ${{ matrix.pkg-path }}
      PKG_NAME: ${{ matrix.pkg-name }}
      PKG_BUILD: ${{ matrix.pkg-build }}
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git    
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\clang
        key: clang-ucrt-x86_64
    - name: Setting makepkg etc
      run: |
        cp pacman-config/makepkg_clang.conf /etc
        cp pacman-config/makepkg-clang /usr/bin
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'        
    - name: Install python dependencies
      shell: bash
      run: |
        pip install meson ninja
    - name: Setting makepkg etc
      run: |
        cp pacman-config/makepkg_clang.conf /etc
        cp pacman-config/makepkg-clang /usr/bin
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)
        cd $PKG_PATH
        if [[ -n "$PKG_BUILD" ]]; then
          makepkg-clang -p $PKG_BUILD
        else
          makepkg-clang
        fi
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        if [[ -n "$PKG_NAME" ]]; then
          ./release-dev.sh $PKG_NAME $PKG_PATH
        else
          ./release-dev.sh $PKG_PATH $PKG_PATH
        fi
  
  dav1d:
    needs: [standalone-pkgs]
    runs-on: windows-2022
    steps:   
    - uses: msys2/setup-msys2@v2
      with:
        cache: false
        location: D:\
        install: base-devel autoconf-wrapper automake-wrapper libtool git    
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\clang
        key: clang-ucrt-x86_64
    - name: Setting makepkg etc
      run: |
        cp pacman-config/makepkg_clang.conf /etc
        cp pacman-config/makepkg-clang /usr/bin
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'        
    - name: Install python dependencies
      shell: bash
      run: |
        pip install meson ninja
    - name: Build
      run: |
        export pypath=$(cygpath -u $pythonLocation)        
        curl -OL https://github.com/${{ github.repository }}/releases/download/dev/xxhash-dev-0.8.2-1-x86_64.pkg.tar.zst
        pacman -U *.zst --noconfirm
        cd dav1d-dev; makepkg-clang
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}   
      shell: bash
      run: |
        ./release-dev.sh dav1d-dev dav1d-dev
```
这个流程有个问题就是：需要等待standalone-pkgs整个job里的所有包全部编译完成后，才能编译需要依赖standalone-pkgs里包的其它包，这无疑会降低整个编译速度。比如dav1d只依赖xxhash。我的要求是只要standalone-pkgs里的xxhash编译完成后就开始编译dav1d。dav1d里的`needs: [standalone-pkgs]`应该改成什么呢？我尝试改成`needs: [standalone-pkgs (xxhash-dev)]`会报错。
