### DISCUSSION TITLE
使用github action 来自动化更新脚本

### DISCUSSION THREAD

**Discussion by Yunuuuu** [hooke007/mpv_PlayKit#402] [mpv 通用]
对于un-release 的scripts，可以直接使用这个https://github.com/BetaHuhn/repo-file-sync-action
对于released的scripts，例如 [uosc](https://github.com/tomasklaen/uosc), 目前没找到很好的Action来处理，不知道有没有很会GitHub action的人给一个示例

**Comment by Yunuuuu** [comment]
一个简单尝试，但是同步uosc还是出问题了
```yml
name: Sync Files
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # sync uosc
      - name: Download uosc
        uses: robinraju/release-downloader@v1.8
        with: 
          repository: "tomasklaen/uosc"
          latest: true
          extract: true
          fileName: "uosc.zip"
          out-file-path: "scripts"

      - name: Sync uosc
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
```
